### ISSUE TITLE
REQ Add Auto User Account + Password

### ISSUE THREAD

**Issue by lolminerxmrig** [Hank-IT/anydesk-management-script#1]
Hi.
plz Add Add Auto User Account + Password Full Access.
Thanks.

**Comment by AlexH-HankIT** [comment]
Hi,

the script does what I currently require. Happy to merge a pull request though.

I'm also available for hire as a freelancer, in case you are based in europe and need help implementing.

Best regards,

Alex.

**Comment by lolminerxmrig** [comment]
yes, very need make user and set password.
me over and over try but not work.

& 'C:\AnyDesk\AnyDesk.exe' --set-password | password123+
& 'C:\AnyDesk\AnyDesk.exe' --get-id | ForEach-Object { Write-Host $_ }

**Comment by lolminerxmrig** [comment]
![image](https://github.com/user-attachments/assets/8c314f91-3bd6-4a0b-8790-f3d25b0f6917)

**Comment by lolminerxmrig** [comment]
can telegram talk?
